<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container85xwDhr\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container85xwDhr/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container85xwDhr.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container85xwDhr\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \Container85xwDhr\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => '85xwDhr',
    'container.build_id' => '51027309',
    'container.build_time' => 1642080194,
], __DIR__.\DIRECTORY_SEPARATOR.'Container85xwDhr');
